const DISPLAY_ITEMS = "DISPLAY_ITEMS";
const LOADING = "LOADING";
const REMOVE_ITEM = "REMOVE_ITEM";
const CLEAR_CART = "CLEAR_CART";
const INCREASE = "INCREASE";
const DECREASE = "DECREASE";

export { CLEAR_CART, DECREASE, DISPLAY_ITEMS, INCREASE, REMOVE_ITEM, LOADING };
